name: Release TypeScript Lib
description: Releases a typescript library
inputs:
  version:
    description: The version to release
    required: true
  root:
    description: The relative path to the root of the TypeScript project. default = root of the repository
    required: true
  user-email:
    description: The email of the user that commits the version file
    required: false
    default: 'build@dolittle.com'
  user-name:
    description: The name of the user that commits the version file
    required: false
    default: 'dolittle-build'

runs:
  using: 'node16'
  main: 'release/index.js'